baseURL = "https://jsbarretto.netlify.com/"
languageCode = "en-us"
title = "Joshua Barretto"

theme = "hugo-resume"

[params]
    firstName = "Joshua"
    lastName = "Barretto"
    address = "Plymouth, UK"
    phone = "07927 037265"
    contactNote = "System software developer" #used in QR code only
    profileImage = "images/profile.png"
    email = "joshua@jsbarretto.com"
    description = "Systems software developer with industry experience."
    favicon = "images/favicon.ico"
	backgroundImage = "images/background.jpg"
	blogURL = "https://jsbarretto.wordpress.com"

    # what sections to display.  Setting to false disables navigation and section.
    showSkills = true
    showProjects = true
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true
	showContact = true
	showContactForm = true
	showBlog = true

	showQr = false

    # do you want to show git hash on page footer and link to repo? Add commit URl for repo here.
    gitCommitPrefix = "https://github.com/zesterer/jsbarretto/commit/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/zesterer/"

#[[params.handles]]
#    name = "Wordpress"
#    link = "https://jsbarretto.wordpress.com/"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/joshua-barretto/"

[[params.handles]]
    name = "YouTube"
    link = "https://www.youtube.com/channel/UCVeOdA6hDpT_SZ4jhuDXAwA"

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/jsbarretto/"

#[[params.handles]]
#    name = "Bitbucket"
#    link = "https://bitbucket.org/eddiewebb/"

#[[params.handles]]
#    name = "Stack Overflow"
#    link = "https://stackoverflow.com/users/story/82880"
#    icon = "stack-overflow" #optional icon attribute used for Font Awesome icons, otherwise the name is lowercased.

#[[params.handles]]
#    name = "Keybase"
#    link = "https://keybase.io/edwardawebb"
#    icon = "key" #optional icon attribute used for Font Awesome icons, otherwise the name is lowercased.

[params.google.analytics]
    trackerID = "XX-123446-01"

[outputs] #only required for search
    home = ["HTML", "JSON"]
